<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-1UNN7PP" ignored="0" name="Default test" tests="9" failures="1" timestamp="22 Jul 2019 16:29:50 GMT" time="87.767" errors="0">
  <testcase name="loginToSite" time="7.538" classname="testcases.UAT_BavarianInnBrokenLinks"/>
  <testcase name="WelcomeMessage" time="8.482" classname="testcases.UAT_BavarianInnBrokenLinks"/>
  <testcase name="uploadReciept" time="4.384" classname="testcases.UAT_BavarianInnBrokenLinks"/>
  <testcase name="profileDisplayed" time="4.161" classname="testcases.UAT_BavarianInnBrokenLinks"/>
  <testcase name="profileCheckBalance" time="6.135" classname="testcases.UAT_BavarianInnBrokenLinks"/>
  <testcase name="profileMyTransactions" time="4.574" classname="testcases.UAT_BavarianInnBrokenLinks">
    <failure type="java.lang.AssertionError" message="expected [Check Card Balance] but found [Transactions]">
      <![CDATA[java.lang.AssertionError: expected [Check Card Balance] but found [Transactions]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at testcases.UAT_BavarianInnBrokenLinks.profileMyTransactions(UAT_BavarianInnBrokenLinks.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- profileMyTransactions -->
  <testcase name="membersOffers" time="20.489" classname="testcases.UAT_BavarianInnBrokenLinks"/>
  <testcase name="membersLocations" time="23.778" classname="testcases.UAT_BavarianInnBrokenLinks"/>
  <testcase name="membersSocial" time="6.696" classname="testcases.UAT_BavarianInnBrokenLinks"/>
</testsuite> <!-- Default test -->
