<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="snipp.test.bav.testcases.UAT_HomePageTest" tests="8" time="41.362" ignored="0" failures="1" timestamp="17 Jul 2019 07:41:44 GMT" skipped="0" hostname="DESKTOP-G1T6KU3" errors="0">
  <testcase name="checkFacebook" time="6.588" classname="snipp.test.bav.testcases.UAT_HomePageTest"/>
  <testcase name="checkYoutube" time="5.332" classname="snipp.test.bav.testcases.UAT_HomePageTest"/>
  <testcase name="loginToSite" time="0.025" classname="snipp.test.bav.testcases.UAT_HomePageTest"/>
  <testcase name="checkYelp" time="19.550" classname="snipp.test.bav.testcases.UAT_HomePageTest"/>
  <testcase name="checkTwitter" time="2.733" classname="snipp.test.bav.testcases.UAT_HomePageTest">
    <failure type="java.lang.AssertionError" message="expected:&lt;Bavarian Inn (@Bavarian_Inn) | Twitter&gt; but was:&lt;Bavarian Inn (@Bavarian_Inn) on Twitter&gt;">
      <![CDATA[java.lang.AssertionError: expected:<Bavarian Inn (@Bavarian_Inn) | Twitter> but was:<Bavarian Inn (@Bavarian_Inn) on Twitter>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at snipp.test.bav.testcases.UAT_HomePageTest.checkTwitter(UAT_HomePageTest.java:228)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- checkTwitter -->
  <testcase name="howItWorks" time="0.533" classname="snipp.test.bav.testcases.UAT_HomePageTest"/>
  <testcase name="register" time="2.310" classname="snipp.test.bav.testcases.UAT_HomePageTest"/>
  <testcase name="faq" time="4.291" classname="snipp.test.bav.testcases.UAT_HomePageTest"/>
</testsuite> <!-- snipp.test.bav.testcases.UAT_HomePageTest -->
